//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimlyFooball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public long TeamId { get; set; }
        public long PlayerId { get; set; }
        public decimal Salary { get; set; }
        public System.DateTime StartContractDate { get; set; }
        public Nullable<System.DateTime> EndContractDate { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
