//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimlyFooball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Position { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
    }
}
